P2_2019MH604_2019ZH601/Models/CasosReportados.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace P2_2019MH604_2019ZH601.Models
{
    public class CasosReportados
    {

        [Key]
        public int idCReportado { get; set; }
        public int IdDpartamento { get; set; }
        public int IdGenero { get; set; }

        public string confirmados { get; set; }
        public string recuperados { get; set; }
        public string fallecidos { get; set; }


    }
}

P2_2019MH604_2019ZH601/Models/Departamentos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace P2_2019MH604_2019ZH601.Models
{
    public class Departamentos
    {
        [Key]
        public int IdDepartamento { get; set; }
        public string Departamento { get; set; }
    }
}

P2_2019MH604_2019ZH601/Models/Generos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace P2_2019MH604_2019ZH601.Models
{
    public class Generos
    {
        [Key]
        public int IdGenero { get; set; }
        public string Genero { get; set; }
    }
}

P2_2019MH604_2019ZH601/Controllers/CovidController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using P2_2019MH604_2019ZH601.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace P2_2019MH604_2019ZH601.Controllers
{
    public class CovidController : Controller
    {

        private readonly dbContext _context;

        public CovidController(dbContext miContexto) 
        {
            this._context = miContexto;
        }
        public IActionResult Index()
        {
            ViewData["Titulo"] = "Registro de Covid";

            IEnumerable<Departamentos> listaDepartamentos = from d in _context.departamentos
                                                            select d;
            List<SelectListItem> ComboDepartamentos = new List<SelectListItem>();

            foreach (Departamentos departamento in listaDepartamentos)
            {
                SelectListItem miOpcion = new SelectListItem
                {
                    Text = departamento.Departamento,
                    Value = departamento.IdDepartamento.ToString()
                };
                ComboDepartamentos.Add(miOpcion);
            }
            ViewBag.ComboDepartamentos = ComboDepartamentos;




            IEnumerable<Generos> listaGeneros = from g in _context.generos
                                                select g;

            List<SelectListItem> ComboGeneros = new List<SelectListItem>();

            foreach (Generos genero in listaGeneros)
            {
                SelectListItem miOpciongenero = new SelectListItem
                {
                    Text = genero.Genero,
                    Value = genero.IdGenero.ToString()
                };
                ComboGeneros.Add(miOpciongenero);
            }
            ViewBag.ComboGeneros = ComboGeneros;

            IEnumerable<CasosReportados> casos = from c in _context.casosReportados select c;
            return View(casos);
        }
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
        [HttpPost]
        public ActionResult insertarDatos(CasosReportados casosReportados)
        {
            var nuevo = new CasosReportados()
            {
                IdDpartamento = casosReportados.IdDpartamento,
                IdGenero= casosReportados.IdGenero,
                confirmados = casosReportados.confirmados,
                recuperados = casosReportados.recuperados,
                fallecidos = casosReportados.fallecidos
            };

            _context.casosReportados.Add(nuevo);
            _context.SaveChanges();

            IEnumerable<CasosReportados> casos = from c in _context.casosReportados select c;

            return RedirectToAction("Index", casos);
        }
    }
}

P2_2019MH604_2019ZH601/Views/Covid/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}
@model IEnumerable<CasosReportados>
<div class="container body-content">
    <div class="text-center">

        <h2 class="display-4">@ViewData["Titulo"]</h2>

        <p>El siguiente formulario es para llevar el registro de casos reportados de </p>

        <p>Covid por departamento y genero.</p>

    </div>
    <br />
    <br />
    <div class="row">
        <h4>Reportar casos</h4>
    </div>
    <br />
    <br />
    @using (Html.BeginForm("insertarDatos", "Covid", FormMethod.Post))
    {
        <div class="row">
            <div class="col-md-6">
                @Html.DropDownList("idDpartamento", (IEnumerable<SelectListItem>)ViewBag.ComboDepartamentos)
            </div>
            <div class="col-md-6">
                @Html.DropDownList("IdGenero", (IEnumerable<SelectListItem>)ViewBag.ComboGeneros)
            </div>

        </div>
        <br />
        <br />

        <div class="row">
            <div class="col-md-4">
                <label>Casos Confirmados</label>
                @Html.TextBox("confirmados", "", new { @class = "form-control" })
            </div>

            <div class="col-md-4">
                <label>Numero de Recuperados</label>
                @Html.TextBox("recuperados", "", new { @class = "form-control" })
            </div>

            <div class="col-md-4">
                <label>Numero de fallecidos</label>
                @Html.TextBox("fallecidos", "", new { @class = "form-control" })
            </div>

        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-success btn-block">Registrar Nuevo caso</button>
            </div>
        </div>
    }

    <div class="container-fluid mt-5">
        <h4 class="mb-3">Casos Reportados</h4>


        <table class="table mr-3 ml-3">
            <thead>
                <tr>
                    <th scope="col">Departamento</th>
                    <th scope="col">Genero</th>
                    <th scope="col">Confirmados</th>
                    <th scope="col">Recuperados</th>
                    <th scope="col">Fallecidos</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var c in Model)
                {

                    <tr>
                        <td>@Html.DisplayFor(item => c.IdDpartamento)</td>
                        <td>@Html.DisplayFor(item => c.IdGenero)</td>
                        <td>@Html.DisplayFor(item => c.confirmados)</td>
                        <td>@Html.DisplayFor(item => c.recuperados)</td>
                        <td>@Html.DisplayFor(item => c.fallecidos)</td>
                    </tr>
                }

            </tbody>
        </table>

    </div>



</div>

P2_2019MH604_2019ZH601/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - P2_2019MH604_2019ZH601</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">P2_2019MH604_2019ZH601</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - P2_2019MH604_2019ZH601 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>